linters:
  Indentation:
    enabled: false
  PropertySortOrder:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  VendorPrefix:
    enabled: false
  ImportantRule:
    enabled: false
  SelectorDepth:
    enabled: false
  PseudoElement:
    enabled: false
